<?php
session_start();
header('Content-Type: application/json');
$_POST['yearMonth'] = '02-17-2026';
if (!isset($_POST['yearMonth']) || !isset($_POST['month_id'])) {
    echo json_encode(["success" => false, "message" => "Missing parameters"]);
    exit;
}

$yearMonth = $_POST['yearMonth'];
$month_id  = $_POST['month_id'];

$employeeName = $_SESSION['ppc']['fullname'];
$employeeNo = $_SESSION['ppc']['emp_no'];

$db = new Postgresql();
$conn = $db->getConnection();

$query = "SELECT email FROM M_ACC_USER_MAINTENANCE WHERE is_notification = TRUE";
$res = pg_query($conn, $query);

$recipients = [];
while ($row = pg_fetch_assoc($res)) {
    $recipients[] = $row['email'];
}

if (empty($recipients)) {
    echo json_encode(["success" => false, "message" => "No recipients found"]);
    exit;
}

$emailSent = implode(",", $recipients);

$html = "
    <div style='padding: 8px; font-family: Arial, sans-serif; font-size: 12pt; color: #333;'>
        <p>A new Journal Distribution has been generated.</p>
        <p>Generated by: <strong>$employeeName</strong></p>
        <p>Date generated: <strong>$yearMonth</strong></p>
    </div>
";

$subject = "JOURNAL DISTRIBUTION GENERATED - $yearMonth";

$emailparams = array(
    'to'        => $emailSent,
    'subject'   => $subject,
    'html'      => $html,
    'nickname'  => "A/P DISTRIBUTION",
);

$serialized_email = serialize($emailparams);

$key = "your_secret_keys";

$encoded = urlencode(
    base64_encode(
        openssl_encrypt($serialized_email, 'AES-256-CBC', $key, 0, $key)
    )
);

$url = "https://webmail.teamglac.com/automail/notif.php?email=" . $encoded;

$mailResponse = file_get_contents($url);

echo json_encode([
    "success" => true,
    "message" => "Email sent",
    "response" => $mailResponse
]);
